# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  username: postgres
  password: postgres
  database: catalogs
  host: localhost

test:
  adapter: postgresql
  username: postgres
  password: postgres
  database: catalog_test
  host: localhost